### ISSUE TITLE
ros2: command not found

### ISSUE THREAD

**Issue by Shroud007** [leo-drive/proto_to_rosbag2#1]
Сompletely followed your instruction, however when I entered the command 
`ros2 run proto_to_rosbag2 proto_to_rosbag2_node --ros-args --params-file ~/rosbag_converter_proto_ws/src/proto_to_rosbag2/params/test_param.yaml`
ros2 writes the following: 
`ros2: command not found`
There are no errors after i entered this command
`colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=1 --packages-up-to proto_to_rosbag2`
![image](https://user-images.githubusercontent.com/62023585/118498645-b1476180-b73f-11eb-949b-c129c606285c.png)
The results are as follows:
![image](https://user-images.githubusercontent.com/62023585/118498715-c3290480-b73f-11eb-969c-f7811aa24111.png)
![image](https://user-images.githubusercontent.com/62023585/118498779-d1772080-b73f-11eb-9586-22d78c48edad.png)

**Comment by xmfcx** [comment]
Ah it's because those are not being built because we are calling `-packages-up-to proto_to_rosbag2`.

Can you run `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=1` instead? So that it builds everything there.

And it should work.

**Comment by Shroud007** [comment]
Now it works. Thanks !
